engines:
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  duplication:
      enabled: true
      config:
        languages:
          javascript:
            mass_threshold: 50
