version: "2"

checks:
  similar-code:
    config:
      threshold: 50

plugins:
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  TSLint:
    enabled: true
