language: generic

services: docker

branches:
  except: /^[0-9]/

env:
  global:
    - TZ='Europe/Oslo'

script: docker build -t "$TRAVIS_REPO_SLUG:$(git rev-list --count HEAD)" .

deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push "$TRAVIS_REPO_SLUG:$(git rev-list --count HEAD)"
  on:
    branch: master

after_deploy:
  - git remote add auth-origin "https://${GITHUB_ACCESS_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
  - git tag "$(git rev-list --count HEAD)"
  - git push auth-origin --tags
