image: navikt/modiapersonoversikt
team: oppfolgingperson
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: isAlive
    initialDelay: 10
  readiness:
    path: isReady
    initialDelay: 10
resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
fasitResources:
  used:
    - alias: loadbalancer:modiapersonoversikt
      resourceType: loadbalancerconfig
    - alias: iadecorator-js
      resourceType: restservice
alertProfiles:
- basic