image: navikt/modiapersonoversikt
port: 80
team: oppfolging
fasitResources:
  used:
    - alias: loadbalancer:modiapersonoversikt
      resourceType: loadbalancerconfig
    - alias: iadecorator-js
      resourceType: restservice
