image: navikt/modiapersonoversikt
port: 80
fasitResources:
  used:
    - alias: loadbalancer:modiapersonoversikt
      resourceType: loadbalancerconfig
    - alias: iadecorator-js
      resourceType: restservice
