csp:
  mode: ENFORCE
  # unsafe-inline trengs her fordi adrum/appd bruker det ved oppsett
  scriptSrc: "'self' 'unsafe-inline' jsagent.adeo.no https://*.hotjar.com https://*.hotjar.io"
  # unsafe-inline trengs her fordi styled-components bruker det
  styleSrc: "'self' 'unsafe-inline'"
  imgSrc: "'self' data: https://*.hotjar.com https://*.hotjar.io"
  fontSrc: "'self' data: https://*.hotjar.com https://*.hotjar.io"
  connectSrc: "'self' eumgw.adeo.no {{ WEBSOCKET_CSP }} {{ ISSO_CSP }} https://*.hotjar.com https://*.hotjar.io"
  # PDF-visning lastes inn via blob-urler
  objectSrc: "blob:"
  frameSrc: "blob: https://*.hotjar.com https://*.hotjar.io"