csp:
  mode: ENFORCE
  # unsafe-inline trengs her fordi adrum/appd bruker det ved oppsett
  scriptSrc: "'self' 'unsafe-inline' jsagent.adeo.no"
  # unsafe-inline trengs her fordi styled-components bruker det
  styleSrc: "'self' 'unsafe-inline'"
  imgSrc: "'self' data:"
  fontSrc: "'self' data:"
  connectSrc: "'self' eumgw.adeo.no {{ WEBSOCKET_CSP }}"


