apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt
  namespace: personoversikt
  cluster: prod-fss
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiapersonoversikt/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiapersonoversikt/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiapersonoversikt/internal/metrics
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3000m
      memory: 1536Mi
  ingresses:
    - https://app.adeo.no/modiapersonoversikt
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  azure:
    application:
      enabled: true
      tenant: nav.no
  env:
    - name: APP_NAME
      value: "modiapersonoversikt"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: IDP_DISCOVERY_URL
      value: "https://isso.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: IDP_CLIENT_ID
      value: "modialogin-p"
    - name: IDP_ISSUER
      value: "https://isso.adeo.no:443/isso/oauth2"
    - name: DELEGATED_LOGIN_URL
      value: "https://app.adeo.no/modialogin/api/start"
    - name: DELEGATED_REFRESH_URL
      value: "https://app.adeo.no/modialogin/api/refresh"
    - name: AUTH_TOKEN_RESOLVER
      value: "modia_ID_token"
    - name: APP_ADEO_DOMAIN
      value: "https://app.adeo.no"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline' jsagent.adeo.no https://*.hotjar.com https://*.hotjar.io;\
      style-src 'self' 'unsafe-inline';\
      img-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      font-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      connect-src 'self' eumgw.adeo.no wss://veilederflatehendelser.adeo.no https://*.hotjar.com https://*.hotjar.io;\
      object-src blob:;\
      frame-src blob: https://*.hotjar.com https://*.hotjar.io;\
      report-uri /frontendlogger/api/warn;"
    - name: REFERRER_POLICY
      value: "no-referrer"