apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-{{q_env}}
  namespace: personoversikt
  cluster: dev-fss
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiapersonoversikt/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiapersonoversikt/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiapersonoversikt/internal/metrics
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app-{{ q_env }}.adeo.no/modiapersonoversikt
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  env:
    - name: APP_NAME
      value: "modiapersonoversikt"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: IDP_DISCOVERY_URL
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: IDP_CLIENT_ID
      value: "modialogin-{{ q_env }}"
    - name: DELEGATED_LOGIN_URL
      value: "https://app-{{ q_env }}.adeo.no/modialogin/api/start"
    - name: AUTH_TOKEN_RESOLVER
      value: "modia_ID_token"
    - name: APP_ADEO_DOMAIN
      value: "https://app-{{ q_env}}.adeo.no"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline' jsagent.adeo.no https://*.hotjar.com https://*.hotjar.io;\
      style-src 'self' 'unsafe-inline';\
      img-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      font-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      connect-src 'self' eumgw.adeo.no wss://veilederflatehendelser-{{ q_env }}.adeo.no https://*.hotjar.com https://*.hotjar.io;\
      object-src blob:;\
      frame-src blob: https://*.hotjar.com https://*.hotjar.io;\
      report-uri /frontendlogger/api/warn;"
    - name: REFERRER_POLICY
      value: "no-referrer"