apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt
  namespace: {{ namespace }}
  cluster: dev-fss
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiapersonoversikt/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiapersonoversikt/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiapersonoversikt/internal/metrics
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3000m
      memory: 1024Mi
  ingresses:
    - https://app-{{ namespace }}.adeo.no/modiapersonoversikt
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /credential/data/dev/isso-rp-user-{{ namespace }}
        mountPath: /var/run/secrets/nais.io/isso-rp-user
      - kvPath: /serviceuser/data/dev/srvmodiapersonoversikt
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: APP_NAME
      value: "modiapersonoversikt"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: IDP_DISCOVERY_URL
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: IDP_CLIENT_ID
      value: "modialogin-{{ namespace }}"
    - name: DELEGATED_LOGIN_URL
      value: "https://app-{{ namespace }}.adeo.no/modialogin/api/start"
    - name: AUTH_TOKEN_RESOLVER
      value: "modia_ID_token"
    - name: APP_ADEO_DOMAIN
      value: "https://app-{{ namespace}}.adeo.no"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline' jsagent.adeo.no https://*.hotjar.com https://*.hotjar.io;\
      style-src 'self' 'unsafe-inline';\
      img-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      font-src 'self' data: https://*.hotjar.com https://*.hotjar.io;\
      connect-src 'self' eumgw.adeo.no wss://veilederflatehendelser-{{ namespace }}.adeo.no https://*.hotjar.com https://*.hotjar.io;\
      object-src blob:;\
      frame-src blob: https://*.hotjar.com https://*.hotjar.io;\
      report-uri /frontendlogger/api/warn;"